config/routes.rb
Rails.application.routes.draw do
  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_page_controller.rb
class IndexPageController < ApplicationController
	def Frontpage
		@message = "hello World"
	end
	
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    @users = User.all
  end

def addFollower
    user.follower
  end
  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:Subject, :Comment, :Date, :image_url, :followers, :users)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_page_helper.rb
module IndexPageHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <center>
    <div class="field">
      <%= f.label :Subject %><br>
      <%= f.text_field :Subject %>
    </div>
  </center>
  <center>
      <div class="field">
        <%= f.label :Comment %><br>
        <%= f.text_field :Comment %>
      </div>
  </center>

  <center>
    <div class="field">
      <%= f.label :Date %><br>
      <%= f.text_field :Date %>
    </div>

  </center>
  
  <center>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url %>
    </div>
  </center>
      <div class="actions">
        <%= f.submit %>
      </div>

  <center>

  </center>
 <% end %>

app/views/pictures/edit.html.erb
<center>
	
	<h1>Editing Picture</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @picture %> |
	<%= link_to 'Back', pictures_path %>
</center>

app/views/pictures/index.html.erb
  <html>
  <head>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  </head>
  <body >
    
    
    <table>
      <tbody>
        
        <nav class="navbar navbar-default navbar-fixed-top" class = "img-responsive">
          <div class="container-fluid">
           

        
            <ul class="nav navbar-nav">
              <li>
                <a class="navbar-brand" href="#">
                  <h2 class = "text-danger"><i>InstantGram </i></h2>
                </a>
              </li>
              <li class = "col-md-2"></li>
              <li class = "col-md-4"><a href="#"><div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for your friends">
                <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
              </div></a></li>
              <li "col-md-2"><a href="#"></a></li>
              <li class = "col-md-1 pull-right"><a href="#">
                <a href="/pictures/new"><img class = "img-responsive" src="http://www.thegreatmedicines.com/wp-content/uploads/2014/12/110767-glowing-green-neon-icon-alphanumeric-plus-sign.png" width = 50 height = 50></a>
                </li>
            </ul>
          </div>
        </nav>
          
        <div class="container">
         
        </div>
      </tbody>  
    </table>
    <table>
      <tbody>
        <tr>
          
        </tr>
      </tbody>  
    </table>
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-default">
  <% fcount = 967 %>     
<table>
  <tbody>
    <tr>
      <td class = "col-md-1">
      </td>
      <td class = "col-md-2">
       <h4>GoldenKookieMakne</h4>
      </td>
      <td class = "col-md-4">
        <img  class = "img-responsive" class = "img-rounded" src="https://ygfamilyartists.files.wordpress.com/2011/06/i_love_kpop_by_xdajoker-d3fg3a0.jpg" width = 700 height = 500>

      </td >
      
      <td class = "col-md-3">
        <table>
          <tbody>
            <tr>
              <h5>Followers: 2.2k</h5>
            </tr>
            <tr>
              <h5>Following: 717</h5>
            </tr>
              

               <button id="up" onclick=>follow</button>
             
            <tr>
            </tr>
          </tbody>
        </table>
            
           
          
      </td>
      <td class = "col-md-1">

      </td>

    </tr>
  </tbody>
</table>



<style type="text/css">
    td:nth-child(1) {
      padding-right: 20px;
      padding-bottom: 50px;
      padding-top: 50px;
}​
</style>


<table>
 
<% count = 0 %>
  <tbody >
   <tr class="row">
    <% @pictures.reverse.each do |picture| %>
      <% count = count + 1 %>
      
        <td class = "col-md-3" > 
            <div class="hovereffect">
              <a href="/pictures/<%=picture.id%>"><img class = "img-responsive" src= "<%= picture.image_url %>"   width = 400 height = 400 ></a>
           
          </div>
  

          </td>
          
          
         <td class = "col-md-1 pull-down">
            <%= link_to 'Edit', edit_picture_path(picture) %>
            <p></p>
            <p></p>

            <%= link_to picture, method: :delete, data: {confirm: 'Are you sure?'} do %>
              <%= image_tag("http://www.frankchimero.com/writing/what-screens-want/trash.jpg", size: "20x20") %>
              <% end %>

          </td>
         
        <% if count ==3 %>
             <% count = 0 %>
             </tr><tr class = "row">
          <% end %>
      
      
    <% end %>

  </tr>
    
  </tbody>
</table>

</body>


    
    
  


  </html>
  

app/views/pictures/new.html.erb
<center>
	<h1>New Picture</h1>
</center>

<center>
	<%= render 'form' %>
</center>
<center>
	<%= link_to 'Back', pictures_path %>
</center>

app/views/pictures/remove.html.erb
<center>
	<%= link_to 'Remove', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
</center>

app/views/pictures/show.html.erb
<center>
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @picture.Subject %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @picture.Comment %>
</p>

<p>
  <strong>Date:</strong>
  <%= @picture.Date %>
</p>

<p>
  <strong>Image url:</strong>
  <img src="<%= @picture.image_url %>" width = 250 height = 250>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |

<%= link_to 'Back', pictures_path %>
	
</center>